language: php
php:
- "5.6"
- "7.0"
- "7.1"
- "7.2"
- "nightly"
- "hhvm"
matrix:
  allow_failures:
  - php: nightly
  - php: hhvm
cache:
  directories:
  - vendor

before_script:
- PHP=$TRAVIS_PHP_VERSION
- if [ $PHP == '5.6' ] ; then composer update -o --ignore-platform-reqs --prefer-lowest --prefer-dist; fi
- if [ $PHP != '5.6' ] ; then composer install -o --prefer-dist; fi

script:
- vendor/bin/phpunit
